name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  start-application:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'    

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: MindfulMichaelJames/star-wars
        ref: main
    - name: Chrome
      run: |
          CHROME_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q --continue -O /tmp/chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip"
          unzip /tmp/chromedriver_linux64.zip -d /tmp
          mv /tmp/chromedriver /usr/local/bin/chromedriver
          chmod +x /usr/local/bin/chromedriver
          wget -q --continue -O /tmp/google-chrome-stable_current_amd64.deb "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
          sudo dpkg -i /tmp/google-chrome-stable_current_amd64.deb
          sudo apt-get install -f
      
    - name: Install dependencies
      run: yarn install

    - name: Build start wars application
      run: yarn build

    - name: Start star wars FE
      run: yarn start &
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

    - name: Grant execute permissions to gradlew
      run: chmod +x ./gradlew
   
    - name: Build with Gradle Wrapper
      run: ./gradlew runCucumberTests  
    
  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
