name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  start-application:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: MindfulMichaelJames/star-wars
        ref: main

    - name: Install pm2
      run: npm install pm2 -g

    - name: Install pm2 to yarn global
      run: yarn global add pm2

    - name: Install dependencies
      run: yarn install

    - name: Build start wars application
      run: yarn build

    - name: Start star wars FE
      run: pm2 start yarn --interpreter bash --name star-wars-ui -- start
      
  test-application:
    name: Run Gradle Tests
    needs: start-application  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Grant execute permissions to gradlew
      run: chmod +x ./gradlew
   
    - name: Build with Gradle Wrapper
      run: ./gradlew runCucumberTests

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
